services:
  tns-energo:
    image: tns-energo
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ENV: prod
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend

  postgres:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql
    environment:
      POSTGRES_DB: "tns-energo"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "sk8McoXvG7Cs"
    ports:
      - "5433:5432"
    networks:
      - backend
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  backend:
    driver: bridge

volumes:
  db-data: