services:
  tns-energo:
    container_name: backend
    image: tns-energo
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ENV: prod
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - backend
    healthcheck:
      test: curl -X GET -f http://localhost:8080/health
      interval: 5s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:latest
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_DB: "tns-energo"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "sk8McoXvG7Cs"
    ports:
      - "5433:5432"
    networks:
      - backend
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  
  minio:
    image: minio/minio:latest
    container_name: minio
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: X8b3nTOBckRF
    volumes:
      - minio_data:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend
  
  nginx:
    image: nginx:latest
    tty: true
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8000:80"
      - "443:443"
    depends_on:
      - tns-energo
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
  minio_data:
