services:
  tns-energo:
    image: tns-energo:latest
    restart: unless-stopped
    container_name: tns-energo
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ENV: dev
      MONGO_CONNECTION_STRING: mongodb://root:ZyRHqr0ojSDVFNUsPvDg@mongo:27017/?connect=direct
      MINIO_USER: root
      MINIO_PASSWORD: lABEgpTa8piMO4wSM91B
    depends_on:
      mongo:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - backend
  
  mongo:
    image: mongo:latest
    restart: unless-stopped
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ZyRHqr0ojSDVFNUsPvDg
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data
    networks:
      - backend
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 5s
      timeout: 5s
      retries: 5
  
  minio:
    image: minio/minio:latest
    restart: unless-stopped
    container_name: minio
    command: server --console-address ":9001" /data/
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: lABEgpTa8piMO4wSM91B
    volumes:
      - minio_data:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend
  
  nginx:
    image: nginx:latest
    restart: unless-stopped
    tty: true
    container_name: nginx
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - tns-energo
    networks:
      - backend
    healthcheck:
      test: service nginx status || exit 1
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
  mongo_data:
  minio_data: