services:
  tns-energo:
    container_name: backend
    image: tns-energo
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ENV: prod
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - backend

  postgres:
    image: postgres:latest
    restart: unless-stopped
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_DB: "tns-energo"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "sk8McoXvG7Cs"
    ports:
      - "5433:5432"
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  minio:
    container_name: minio
    image: bitnami/minio:latest
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "X8b3nTOBckRF"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
  minio_data:
