name: Docker Compose Build & Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get short SHA
        id: vars
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Stop and remove previous containers
        run: |
          docker compose down || true

      - name: Build and run containers with docker-compose
        run: |
          docker compose up -d --build

      - name: Cleanup old dangling images
        run: docker image prune -f
